# -- GIT: Forgejo --
services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:10
    restart: unless-stopped
    ports:
      - "${FORGEJO_HTTP_PORT:-3001}:3000"
      - "${FORGEJO_SSH_PORT:-222}:22"
    volumes:
      - ${MEDIA_ROOT}/forgejo/data:/data
    environment:
      USER_UID: "${PUID:-1000}"
      USER_GID: "${PGID:-1000}"
      FORGEJO__server__ROOT_URL: "https://git.keruhomelab.com/"
      FORGEJO__server__DOMAIN: "git.keruhomelab.com"
      FORGEJO__server__SSH_DOMAIN: "git.keruhomelab.com"
      FORGEJO__server__SSH_PORT: "22"
    networks:
      homelab:
        aliases:
          - forgejo

networks:
  homelab:
    external: true
    name: homelab-infra_homelab
